name: x_clone
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  #Uİ
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.17

  #BUSİNESS
  go_router: ^14.4.1
  device_preview_plus: ^2.2.0
  gap: ^3.0.1
  numeral: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true


  assets:
  - assets/photos/x_picture.jpg
  - assets/icons/twitter-alert-6.svg
  - assets/icons/twitter-analytics.svg
  - assets/icons/twitter-home.svg
  - assets/icons/twitter-like-outline.svg
  - assets/icons/twitter-message.svg
  - assets/icons/twitter-news.svg
  - assets/icons/twitter-reply-outline.svg
  - assets/icons/twitter-retweet.svg
  - assets/icons/twitter-search.svg
  - assets/icons/twitter-verified.svg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
